# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0002_delete_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=200)),
                ('sub_text', models.TextField(default='')),
                ('sub_pub', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
